### ISSUE TITLE
skipping pixels

### ISSUE THREAD

**Issue by xKarmaSs** [Karalinga/ArduinoHostShieldMouseAndScrollWheel#1]
Hi Karalinga,

i did all the steps you said and my mouse works scroll wheel works to but there is a problem when i move my mouse fast to right then i make like a full 360 looks like i am skipping a lot of pixels but when i do the same with to the left side nothing happens and the mouse moves normal without any issue? Do you maybe know how to fix this bug i am using a razer viper mini i tryed to lower the hz rate to 500 and i also tryed lowering my dpi when still same resulte move the mouse a bit to quick to the right and i am skipping like 500 pixels are do like a full 180 turn... i am not sure what i am missing maybe you know what is going on :D

**Comment by Karalinga** [comment]
Hey mate, it's 2 am here, I will get back to you in the morning if that's
OK with you.
Regards,
Max.

**Comment by Karalinga** [comment]
Ok so, I'm not certain what the problem is. I don't have a razer viper mini but I have tested it with multiple mice and some razer mice too that have worked fine. Maybe check which usbhostshieldmaster2.0 version you are running in your Arduino libraries. The first thing that came to mind is the Arduino inability to move more than 127 pixels in one move, which I generally wouldn't imagine being a problem, however it might be depending on how the inputs come from the mouse and what the polling rate is on the mouse.  But first try and use the host shield library 1.6.0 which is what I am using currently, and maybe try with another mouse too if you have one.

**Comment by xKarmaSs** [comment]
polling rate 1000hz when i use 125hz its even worse i downgraded to host shield library 1.6.0 still same thing i tryed a Zowie EC2-A but that mouse is just moving left and right no real up and down working guess the zowie has a diffrient byte stream i think the problem is this one "Arduino inability to move more than 127 pixels in one move" but still does not explain why when i move the mouse fast to the left that its not jumping/skipping pixels and when i do the same for the right movement then its jumping/skipping pixels i tryed to showcase it maybe you can understand better after: https://streamable.com/mjt0ov

**Comment by Karalinga** [comment]
Hey, when I get up in the morning I will write up a new arduino code that,
instead of moving the mouse, prints the outputs in the serial monitor. If
you know how to so this it's even easier, essentially we just change the
command that moves the mouse to instead Serial.println(x,y,z). So that we
can see what values arise,  if the value is greater than 127 then it should
be an easy fix, we just divide the number by 127, get the value and run a
for loop that many times and move it, then move the remainder. I have
written this already my computer is just off since I am heading to bed.

**Comment by Karalinga** [comment]
![image](https://user-images.githubusercontent.com/49670475/181669061-92da10c3-08a8-4c9f-b2b0-20fbf03757c2.png)
These are the changes I made to the file to check the mouse inputs. 
![image](https://user-images.githubusercontent.com/49670475/181668989-41288a8e-93ba-401c-9bc0-fc8e3acb1646.png)
(These are the values I get when I move my mouse quickly)

Below is the code to move more than 127, maybe add this and call this instead of Mouse.move(mi->dX, mi->dY);
I don't know why one direction works and the other doesn't but the fact that the higher polling rate helps suggests that this might fix it. Let me know how it goes :) .

void moveMouse(long x, long y) {
  fullDist = max(abs(x), abs(y));
  count = (int) (fullDist / 127);
  moveX = x / (count + 1);
  moveY = y / (count + 1);
  for (int i = 0; i < count; i++) {
    Mouse.begin();
    Mouse.move(moveX, moveY);
    Mouse.end();
  }
  remainderX = x - (moveX * count);
  remainderY = y - (moveY * count);
  if (remainderX != 0 || remainderY != 0) {
    Mouse.begin();
    Mouse.move(remainderX, remainderY);
    Mouse.end();
  }
}

**Comment by xKarmaSs** [comment]
it got better but still happening from time to time maybe its a mouse/sensor issue.
serial monitor: https://gyazo.com/b8de326f4453a073b18de893147f02b0
my implementation: https://gyazo.com/5b04cf3b80dd342203ef8e04eb1d9bba
result: https://streamable.com/8mf9u3
i guess there is nothing one of us can do i just have to life with it :D

**Comment by Karalinga** [comment]
Yeah I'm not sure what the issuer is here, it might be something to do with how the mouse sends inputs, but if you see it randomly just go to 127 like it did in the screenshot for almost no reason, then maybe you could just have an if statement that excludes inputs of >100 or <100 (if its a big jump just ignore it). or possibly only on one direction since it happens only going right like if (mi-Dx <100): continue the move mouse event. But yeah I'm not really sure what the issue is and I haven't come across it yet, thank you for the issue though I will do some more research myself but it has been a good experience nonetheless. Sorry I couldn't solve the issue.

**Comment by xKarmaSs** [comment]
I tryed doing that "if (mi-Dx <100): continue" but it has no effect ?
